config/routes.rb
Rails.application.routes.draw do
  get 'attendees/new'

  get 'events/new'

  #root 'static_pages#home'
  root 'events#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'events#new'
  post '/signup',  to: 'events#create'
  get '/checkin', to: 'attendees#new'
  post '/checkin',  to: 'attendees#create'
  delete '/logout',  to: 'events#destroy'

  resources :events
  resources :attendees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false, scope: :event_id, message: "You can only check into this event once"}
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendees, dependent: :destroy
	validates :name, presence: true, length: { maximum: 50 }
	validates :starts_at, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def new
  	@attendee = Attendee.new
  end

  def create
  	 @attendee = Attendee.new(attendee_params)

    if @attendee.save
      flash[:success] = "Thank you for checking-in"
      redirect_to root_path
    else
     render 'new'
    end
  end

  def attendee_params
      params.require(:attendee).permit(:name, :email, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
  end

  def index
  	@events = Event.all
  	@attendees = Attendee.all
  end

  def new
  	@event = Event.new
  end

  def create
  	 @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Thank you for registering your event"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
  	e = Event.find(params[:id])
  	# no longer need this, taken care of through has_many association
  	#Attendee.all.each do |a|
  	#  if a.event_name == e.name
  	#  	a.destroy
  	#  end 
  	#end
  	e.destroy
    flash[:success] = "Event deleted"
    redirect_to root_url
  end

  def event_params
      params.require(:event).permit(:name, :starts_at)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Event Scheduling App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attendees/new.html.erb
<% provide(:title, 'Check-In') %>
<h1>Check-In</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@attendee, url: checkin_path) do |f| %>
      <%= render 'shared/error_messages_attendees' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :event_id %>
      <%= f.collection_select :event_id, Event.all, :id, :name, class: 'form-control'%>

      <%= f.submit "Check-In", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Event Scheduling App</h1>

  <h2>
    This is the home page for Josh Beasley's
    event scheduling application.
  </h2>


    <div class = 'create'><%= link_to "Create Event", signup_path, class: "btn btn-lg btn-primary" %></div>
    <div class = 'delete' ><%= link_to "Check-In", checkin_path, class: "btn btn-lg btn-success" %></div>

  

  <% @events.each do |event| %>
	<div class = "event">
	  <h2>
	  	<div class = "name"><%= event.name %></div>
	  	<div class = "time">Event Time: <%= event.starts_at %></div>
      <div class = 'attendee'>Attendees:</div>
      <div>
        <% @attendees.each do |attendee| %>
          <% if attendee.event == event %>
            <div class = 'list'>
              <h4>Name: <%= attendee.name %> Check-In Time: <%= attendee.updated_at %>
              </h4>
            </div>
          <% end %>
        <% end %>
      </div>
	  	<div class = 'delete'><%= link_to "Delete Event", event, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-lg btn-danger" %></div>
	  </h2>
	</div>
  <% end %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/events/new.html.erb
<% provide(:title, 'Create Event') %>
<h1>Create Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :starts_at, class: 'form-control' %>
      <%= f.datetime_select :starts_at, :ampm => true, :minute_step => 15 %>

      <%= f.submit "Create Event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class = "event">
	  <h2>
	  	<div class = "name"><%= @event.name %></div>
	  	<div class = "time"><%= @event.starts_at %></div>
	  	<div class = "delete"><%= link_to "Delete Event", '#', class: "btn btn-lg btn-danger" %></div>
	  </h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    An event scheduling app created by Josh Beasley
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Event Scheduling App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_attendees.html.erb
<% if @attendee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@attendee.errors.count, "error") %>.
    </div>
    <ul>
    <% @attendee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      My name is Josh. This website was created for my SDMP Training.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This is the official help page for Josh Beasley's Event Scheduling App. If you need help... I really don't know what you should do. I left this page in the website because I liked the way it looks, but it's actually completely useless :)
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>